
services:
  water-detection:
    build: .
    container_name: water-detection-simulation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - TF_CPP_MIN_LOG_LEVEL=3
      - TF_ENABLE_ONEDNN_OPTS=0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app

