"""
TFLite Model to C Array Converter for ESP32-S3
==============================================
Converts a TensorFlow Lite model (.tflite) to a C byte array
that can be included in ESP32 firmware.

Usage:
    python tflite_to_c_array.py <input.tflite> [output.h]
"""

import sys
import os

def convert_tflite_to_c_array(tflite_path, output_path=None):
    """
    Convert TFLite model to C header file with byte array
    
    Args:
        tflite_path: Path to .tflite file
        output_path: Path to output .h file (optional)
    """
    if not os.path.exists(tflite_path):
        print(f"Error: File not found: {tflite_path}")
        return False
    
    # Read the TFLite model
    with open(tflite_path, 'rb') as f:
        tflite_model = f.read()
    
    model_size = len(tflite_model)
    
    # Generate output filename if not provided
    if output_path is None:
        base_name = os.path.splitext(os.path.basename(tflite_path))[0]
        output_path = os.path.join(os.path.dirname(tflite_path), f"{base_name}_model.h")
    
    # Create variable name from filename
    var_name = os.path.splitext(os.path.basename(output_path))[0].replace('-', '_').replace('.', '_')
    
    # Generate C header file
    with open(output_path, 'w') as f:
        f.write(f"// Auto-generated C array from {os.path.basename(tflite_path)}\n")
        f.write(f"// Model size: {model_size:,} bytes\n")
        f.write(f"// Generated by: tflite_to_c_array.py\n\n")
        
        f.write(f"#ifndef {var_name.upper()}_H\n")
        f.write(f"#define {var_name.upper()}_H\n\n")
        
        f.write(f"// Model data length\n")
        f.write(f"const unsigned int {var_name}_len = {model_size};\n\n")
        
        f.write(f"// Model data (aligned to 4 bytes for ESP32)\n")
        f.write(f"alignas(4) const unsigned char {var_name}[] = {{\n")
        
        # Write bytes in rows of 12
        for i in range(0, model_size, 12):
            chunk = tflite_model[i:i+12]
            hex_values = ', '.join([f'0x{b:02x}' for b in chunk])
            f.write(f"  {hex_values}")
            if i + 12 < model_size:
                f.write(',')
            f.write('\n')
        
        f.write("};\n\n")
        f.write(f"#endif  // {var_name.upper()}_H\n")
    
    print(f"✓ Converted: {tflite_path}")
    print(f"  Model size: {model_size:,} bytes ({model_size/1024:.2f} KB)")
    print(f"  Output: {output_path}")
    print(f"  Variable name: {var_name}")
    print(f"  Array length: {var_name}_len")
    
    return True

def main():
    if len(sys.argv) < 2:
        print("Usage: python tflite_to_c_array.py <input.tflite> [output.h]")
        print("\nExample:")
        print("  python tflite_to_c_array.py esp32_model/esp32_autoencoder_int8.tflite")
        sys.exit(1)
    
    tflite_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None
    
    success = convert_tflite_to_c_array(tflite_path, output_path)
    
    if success:
        print("\n✓ Conversion complete!")
        print("\nNext steps:")
        print("  1. Copy the .h file to your ESP32 project")
        print("  2. Include it in your Arduino/ESP-IDF code:")
        print(f"     #include \"{os.path.basename(output_path if output_path else 'model.h')}\"")
        print("  3. Use the model array with TensorFlow Lite Micro")
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
